### ISSUE TITLE
ISBAT: Search products by SKU number ONLY!

### ISSUE THREAD

**Issue by yordivd** [co-cart/cocart-products#25]
**Is this enhancement related to a problem? Please describe.**
What this plugin (and also the official woocommerce v3 rest api) is missing, is a way to search product variations by sku number.
Many times the sku of the variation is used as barcode in physical stores. When you are developing a POS for woocommerce and a user scan this barcode/sku you want to be able to search directly inside the variations also.

**Describe the solution you'd like**
A "List product variations" endpoint that does not require parent product id

**Comment by seb86** [comment]
@yordivd Thank you for your request. I was a little confused by your issue as you did not explain the title clearly. Searching products by SKU is already available but your asking to be able to search by JUST the SKU number without the product ID, correct?

**Comment by yordivd** [comment]
@seb86 yes that is correct. I think it's crucial if you want to create a POS application for woocommerce that doesn't sync everything to a local database.

**Comment by seb86** [comment]
Gotcha. Will put it on the roadmap. Currently updating the documentation for tweaks made for the next release. Then updates for API v2

**Comment by seb86** [comment]
Done and ready for next CoCart Pro update
